spring:
  application:
    name: payment-service

server:
  port: 8083

app:
  kafka:
    topics:
      reservation-created: reservation-service.reservation-created
      payment-confirmed: payment-service.payment-confirmed
      payment-failed: payment-service.payment-failed
    dlt-topic:
      payment-service: payment.service.dlt
  outbox:
    scheduler-fixed-rate: 5000 # 5 seconds

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always